[username]
format = '[$user]($style)@' # just use @ instead of in
style_user = 'green'

[hostname]
ssh_symbol = '' # don't display the weird earth emoji
style = 'green dimmed'

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style)"
style = "bright-black"

